source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoolPhysics2D_Example' do
  pod "CoolPhysics2D", :path => "../"
end

target 'CoolPhysics2D_Tests' do
  pod "CoolPhysics2D", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
